import i18n from "./locales/index";

function strings() {
  return {
    home: i18n.t("home", { defaultValue: "" }),
    app_name: i18n.t("app_name", { defaultValue: "" }),
    updating: i18n.t("updating", { defaultValue: "" }),
    ai_voice: i18n.t("ai_voice", { defaultValue: "" }),
    templates: i18n.t("templates", { defaultValue: "" }),
    my_voice: i18n.t("my_voice", { defaultValue: "" }),
    history: i18n.t("history", { defaultValue: "" }),
    language: i18n.t("language", { defaultValue: "" }),
    default: i18n.t("default", { defaultValue: "" }),
    german: i18n.t("german", { defaultValue: "" }),
    english: i18n.t("english", { defaultValue: "" }),
    spanish: i18n.t("spanish", { defaultValue: "" }),
    french: i18n.t("french", { defaultValue: "" }),
    italian: i18n.t("italian", { defaultValue: "" }),
    vietnamese: i18n.t("vietnamese", { defaultValue: "" }),
    japanese: i18n.t("japanese", { defaultValue: "" }),
    resetting_language: i18n.t("resetting_language", { defaultValue: "" }),
    settings: i18n.t("settings", { defaultValue: "" }),
    go_to_premium: i18n.t("go_to_premium", { defaultValue: "" }),
    enjoy_all_benefits: i18n.t("enjoy_all_benefits", { defaultValue: "" }),
    upgrade: i18n.t("upgrade", { defaultValue: "" }),
    save: i18n.t("save", { defaultValue: "" }),
    email_support: i18n.t("email_support", { defaultValue: "" }),
    share_with_friends: i18n.t("share_with_friends", { defaultValue: "" }),
    rate_it: i18n.t("rate_it", { defaultValue: "" }),
    about_us: i18n.t("about_us", { defaultValue: "" }),
    terms_of_use: i18n.t("terms_of_use", { defaultValue: "" }),
    privacy_policy: i18n.t("privacy_policy", { defaultValue: "" }),
    device_id: i18n.t("device_id", { defaultValue: "" }),
    app_link: i18n.t("app_link", { defaultValue: "" }),
    please_install_app: i18n.t("please_install_app", { defaultValue: "" }),
    setting: i18n.t("setting", { defaultValue: "" }),
    create: i18n.t("create", { defaultValue: "" }),
    get_pro: i18n.t("get_pro", { defaultValue: "" }),
    use: i18n.t("use", { defaultValue: "" }),
    free_tries_to_test: i18n.t("free_tries_to_test", { defaultValue: "" }),
    we_are_generating: i18n.t("we_are_generating", { defaultValue: "" }),
    step_1_pick_song: i18n.t("step_1_pick_song", { defaultValue: "" }),
    type_your_text: i18n.t("type_your_text", { defaultValue: "" }),
    paste: i18n.t("paste", { defaultValue: "" }),
    search_or_paste_ytb_link: i18n.t("search_or_paste_ytb_link", {
      defaultValue: "",
    }),
    paste_err: i18n.t("paste_err", { defaultValue: "" }),
    step_2_select_voice: i18n.t("step_2_select_voice", { defaultValue: "" }),
    generate: i18n.t("generate", { defaultValue: "" }),
    ok: i18n.t("ok", { defaultValue: "" }),
    toast_result_processing: i18n.t("toast_result_processing", {
      defaultValue: "",
    }),
    toast_result_completed: i18n.t("toast_result_completed", {
      defaultValue: "",
    }),
    toast_result_failed: i18n.t("toast_result_failed", { defaultValue: "" }),
    create_your_voice: i18n.t("create_your_voice", { defaultValue: "" }),
    pending: i18n.t("pending", { defaultValue: "" }),
    failed: i18n.t("failed", { defaultValue: "" }),
    how_to_copy_a: i18n.t("how_to_copy_a", { defaultValue: "" }),
    link_from_ytb: i18n.t("link_from_ytb", { defaultValue: "" }),
    tab_share_ytb_video: i18n.t("tab_share_ytb_video", { defaultValue: "" }),
    then_tab_copy: i18n.t("then_tab_copy", { defaultValue: "" }),
    paste_ytb_link: i18n.t("paste_ytb_link", { defaultValue: "" }),
    got_it: i18n.t("got_it", { defaultValue: "" }),
    invalid_ytb_url: i18n.t("invalid_ytb_url", { defaultValue: "" }),
    title_not_found: i18n.t("title_not_found", { defaultValue: "" }),
    err_get_video_title: i18n.t("err_get_video_title", { defaultValue: "" }),
    you_have_max_turn: i18n.t("you_have_max_turn", { defaultValue: "" }),
    this_not_valid_ytb_link: i18n.t("this_not_valid_ytb_link", {
      defaultValue: "",
    }),
    you_not_have_add_ytb_link: i18n.t("you_not_have_add_ytb_link", {
      defaultValue: "",
    }),
    you_have: i18n.t("you_have", { defaultValue: "" }),
    tries_left_to_keep: i18n.t("tries_left_to_keep", { defaultValue: "" }),
    exploring_ai: i18n.t("exploring_ai", { defaultValue: "" }),
    you_not_have_free_songs: i18n.t("you_not_have_free_songs", {
      defaultValue: "",
    }),
    start_now_see_ai_can: i18n.t("start_now_see_ai_can", { defaultValue: "" }),
    ok_try_now: i18n.t("ok_try_now", { defaultValue: "" }),
    pick_song: i18n.t("pick_song", { defaultValue: "" }),
    enter_text: i18n.t("enter_text", { defaultValue: "" }),
    unlimited_official_voice: i18n.t("unlimited_official_voice", {
      defaultValue: "",
    }),
    turbo_processing: i18n.t("turbo_processing", { defaultValue: "" }),
    no_ads: i18n.t("no_ads", { defaultValue: "" }),
    special_offer: i18n.t("special_offer", { defaultValue: "" }),
    yearly_sub: i18n.t("yearly_sub", { defaultValue: "" }),
    year: i18n.t("year", { defaultValue: "" }),
    premium: i18n.t("premium", { defaultValue: "" }),
    weekly_sub: i18n.t("weekly_sub", { defaultValue: "" }),
    week: i18n.t("week", { defaultValue: "" }),
    continue: i18n.t("continue", { defaultValue: "" }),
    restore: i18n.t("restore", { defaultValue: "" }),
    content_premium_android: i18n.t("content_premium_android", {
      defaultValue: "",
    }),
    content_premium_ios: i18n.t("content_premium_ios", { defaultValue: "" }),
    suggested: i18n.t("suggested", { defaultValue: "" }),
    oop_no_result: i18n.t("oop_no_result", { defaultValue: "" }),
    let_try_new_search: i18n.t("let_try_new_search", { defaultValue: "" }),
    select_song: i18n.t("select_song", { defaultValue: "" }),
    paste_link: i18n.t("paste_link", { defaultValue: "" }),
    hide: i18n.t("hide", { defaultValue: "" }),
    create_songs_faster: i18n.t("create_songs_faster", { defaultValue: "" }),
    notification_warning_delete_after_3_days: i18n.t(
      "notification_warning_delete_after_3_days",
      { defaultValue: "" },
    ),
    dismiss: i18n.t("dismiss", { defaultValue: "" }),
    select: i18n.t("select", { defaultValue: "" }),
    unselect: i18n.t("unselect", { defaultValue: "" }),
    select_all: i18n.t("select_all", { defaultValue: "" }),
    delete: i18n.t("delete", { defaultValue: "" }),
    processing: i18n.t("processing", { defaultValue: "" }),
    unable_to_process_project: i18n.t("unable_to_process_project", {
      defaultValue: "",
    }),
    delete_confirmation: i18n.t("delete_confirmation", { defaultValue: "" }),
    content_confirm_delete: i18n.t("content_confirm_delete", {
      defaultValue: "",
    }),
    cancel: i18n.t("cancel", { defaultValue: "" }),
    sounds_amazing: i18n.t("sounds_amazing", { defaultValue: "" }),
    create_new: i18n.t("create_new", { defaultValue: "" }),
    share: i18n.t("share", { defaultValue: "" }),
    join_us: i18n.t("join_us", { defaultValue: "" }),
    library_required: i18n.t("library_required", { defaultValue: "" }),
    please_grant_library: i18n.t("please_grant_library", { defaultValue: "" }),
    success: i18n.t("success", { defaultValue: "" }),
    audio_shared_success: i18n.t("audio_shared_success", { defaultValue: "" }),
    audio_download_success: i18n.t("audio_download_success", {
      defaultValue: "",
    }),
    audio_download_err: i18n.t("audio_download_err", { defaultValue: "" }),
    video_download_success: i18n.t("video_download_success", {
      defaultValue: "",
    }),
    video_download_err: i18n.t("video_download_err", { defaultValue: "" }),
    saved_song_success: i18n.t("saved_song_success", { defaultValue: "" }),
    content_save_song_success: i18n.t("content_save_song_success", {
      defaultValue: "",
    }),
    cool: i18n.t("cool", { defaultValue: "" }),
    enjoying_so_far: i18n.t("enjoying_so_far", { defaultValue: "" }),
    content_rate_result: i18n.t("content_rate_result", { defaultValue: "" }),
    not_really: i18n.t("not_really", { defaultValue: "" }),
    love_it: i18n.t("love_it", { defaultValue: "" }),
    content_feedback_result: i18n.t("content_feedback_result", {
      defaultValue: "",
    }),
    feedback: i18n.t("feedback", { defaultValue: "" }),
    try_training_voice: i18n.t("try_training_voice", { defaultValue: "" }),
    to_make_more_professional: i18n.t("to_make_more_professional", {
      defaultValue: "",
    }),
    later: i18n.t("later", { defaultValue: "" }),
    ok_try: i18n.t("ok_try", { defaultValue: "" }),
    step_1: i18n.t("step_1", { defaultValue: "" }),
    choose_source: i18n.t("choose_source", { defaultValue: "" }),
    record_or_upload: i18n.t("record_or_upload", { defaultValue: "" }),
    record_voice: i18n.t("record_voice", { defaultValue: "" }),
    upload_audio_file: i18n.t("upload_audio_file", { defaultValue: "" }),
    ytb_link: i18n.t("ytb_link", { defaultValue: "" }),
    step_2: i18n.t("step_2", { defaultValue: "" }),
    content_paste_ytb_link: i18n.t("content_paste_ytb_link", {
      defaultValue: "",
    }),
    permission_not_granted: i18n.t("permission_not_granted", {
      defaultValue: "",
    }),
    micro_required: i18n.t("micro_required", { defaultValue: "" }),
    storage_required: i18n.t("storage_required", { defaultValue: "" }),
    record_your_voice: i18n.t("record_your_voice", { defaultValue: "" }),
    please_record_lease_30_s: i18n.t("please_record_lease_30_s", {
      defaultValue: "",
    }),
    recording_time: i18n.t("recording_time", { defaultValue: "" }),
    press_to_start_record: i18n.t("press_to_start_record", {
      defaultValue: "",
    }),
    press_to_stop_record: i18n.t("press_to_stop_record", { defaultValue: "" }),
    done: i18n.t("done", { defaultValue: "" }),
    press_to_pause_record: i18n.t("press_to_pause_record", {
      defaultValue: "",
    }),
    press_to_resume_record: i18n.t("press_to_resume_record", {
      defaultValue: "",
    }),
    the_recording_duration_than_30s: i18n.t("the_recording_duration_than_30s", {
      defaultValue: "",
    }),
    preparing_record: i18n.t("preparing_record", { defaultValue: "" }),
    upload: i18n.t("upload", { defaultValue: "" }),
    total_size_and_length_not_exceed_limits: i18n.t(
      "total_size_and_length_not_exceed_limits",
      { defaultValue: "" },
    ),
    my_record: i18n.t("my_record", { defaultValue: "" }),
    add_audio_file: i18n.t("add_audio_file", { defaultValue: "" }),
    record: i18n.t("record", { defaultValue: "" }),
    file_size_exceed_50mb: i18n.t("file_size_exceed_50mb", {
      defaultValue: "",
    }),
    file_duration_exceed_15m: i18n.t("file_duration_exceed_15m", {
      defaultValue: "",
    }),
    step_3: i18n.t("step_3", { defaultValue: "" }),
    customize_voice: i18n.t("customize_voice", { defaultValue: "" }),
    give_custom_voice_make_it_personal: i18n.t(
      "give_custom_voice_make_it_personal",
      { defaultValue: "" },
    ),
    choose_option: i18n.t("choose_option", { defaultValue: "" }),
    camera: i18n.t("camera", { defaultValue: "" }),
    choose_from_library: i18n.t("choose_from_library", { defaultValue: "" }),
    preparing_voice: i18n.t("preparing_voice", { defaultValue: "" }),
    custom_voice: i18n.t("custom_voice", { defaultValue: "" }),
    you_not_select_photo: i18n.t("you_not_select_photo", { defaultValue: "" }),
    you_not_named_it: i18n.t("you_not_named_it", { defaultValue: "" }),
    enjoying: i18n.t("enjoying", { defaultValue: "" }),
    tap_star_rate_it: i18n.t("tap_star_rate_it", { defaultValue: "" }),
    rate_us: i18n.t("rate_us", { defaultValue: "" }),
    starts: i18n.t("starts", { defaultValue: "" }),
    terrible: i18n.t("terrible", { defaultValue: "" }),
    bad: i18n.t("bad", { defaultValue: "" }),
    good: i18n.t("good", { defaultValue: "" }),
    excellent: i18n.t("excellent", { defaultValue: "" }),
    audio: i18n.t("audio", { defaultValue: "" }),
    video: i18n.t("video", { defaultValue: "" }),
    no_project_yet: i18n.t("no_project_yet", { defaultValue: "" }),
    start_ai_song_now: i18n.t("start_ai_song_now", { defaultValue: "" }),
    create_now: i18n.t("create_now", { defaultValue: "" }),
    per_year_cancel_anytime: i18n.t("per_year_cancel_anytime", {
      defaultValue: "",
    }),
    best_value: i18n.t("best_value", { defaultValue: "" }),
    ai_cover: i18n.t("ai_cover", { defaultValue: "" }),
    version: i18n.t("version", { defaultValue: "" }),
    create_voice_failed: i18n.t("create_voice_failed", { defaultValue: "" }),
    create_cover_failed: i18n.t("create_cover_failed", { defaultValue: "" }),
    delete_success: i18n.t("delete_success", { defaultValue: "" }),
    delete_failed: i18n.t("delete_failed", { defaultValue: "" }),
    cannot_finish_transaction: i18n.t("cannot_finish_transaction", {
      defaultValue: "",
    }),
    err_try_again: i18n.t("err_try_again", { defaultValue: "" }),
    cannot_get_deviceid: i18n.t("cannot_get_deviceid", { defaultValue: "" }),
    restore_failed: i18n.t("restore_failed", { defaultValue: "" }),
    edit_phrase: i18n.t("edit_phrase", { defaultValue: "" }),
    downloading: i18n.t("downloading", { defaultValue: "" }),
    loading: i18n.t("loading", { defaultValue: "" }),
  };
}
export default strings;
